/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.faculty;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.CourseSchedule.CourseOffer;
import model.CourseSchedule.Seat;
import model.CourseSchedule.SeatAssignment;
import model.Department.Department;
import model.Persona.Faculty.FacultyAssignment;
import model.Persona.Faculty.FacultyProfile;

/**
 *
 * @author piyush
 */
public class ViewClassesJPanel extends javax.swing.JPanel {
JPanel workArea;
FacultyProfile f;
String selectedSchedule;
Department d;
    /**
     * Creates new form ViewClassesJPanel
     */
    public ViewClassesJPanel(JPanel workArea , FacultyProfile f, Department d) {
        this.workArea = workArea;
        this.f = f;
        this.d=d;
        initComponents();
        //populateTable();
        refreshTable();
        populateComboBox();
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        viewClassJLabel = new javax.swing.JLabel();
        manageJButton = new javax.swing.JButton();
        semesterComboBox = new javax.swing.JComboBox<>();
        semesterLabel = new javax.swing.JLabel();

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Class Name", "Room Number", "No. of Students"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable);

        viewClassJLabel.setText("View Classes");

        manageJButton.setText("Manage Class");
        manageJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageJButtonActionPerformed(evt);
            }
        });

        semesterComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semesterComboBoxActionPerformed(evt);
            }
        });

        semesterLabel.setText("Semester:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(226, 226, 226)
                                .addComponent(manageJButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(viewClassJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(semesterLabel)
                        .addGap(18, 18, 18)
                        .addComponent(semesterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(semesterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(semesterLabel)
                    .addComponent(viewClassJLabel))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(manageJButton)
                .addContainerGap(168, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageJButtonActionPerformed
        int index = jTable.getSelectedRow();
        if(index<0){
            JOptionPane.showMessageDialog(this,"Invalid Selection");
        }
        else{
        CourseOffer c = f.getFacultyAssignment().get(index).getCourseOffer();
        ManageClassJPanel m = new ManageClassJPanel(workArea,c);
        workArea.add("ManageClassesJPanel", m);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
      
       
        
        }
    }//GEN-LAST:event_manageJButtonActionPerformed

    private void semesterComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semesterComboBoxActionPerformed
        Object o = semesterComboBox.getSelectedItem();
       if(o!=null){
        selectedSchedule = semesterComboBox.getSelectedItem().toString();
        refreshTable();
       }
    }//GEN-LAST:event_semesterComboBoxActionPerformed

         public void populateTable(){
        DefaultTableModel table = (DefaultTableModel)jTable.getModel();
        table.setRowCount(0);
        for(FacultyAssignment fa : f.getFacultyAssignment()){
           
            Object[] row = new Object[3];
            row[0] = fa.getCourseOffer().getCourseNumber();
            row[1] = fa.getCourseOffer().getRoomNumber();
            row[2] = fa.getCourseOffer().getRegisteredSeats();
            
            table.addRow(row);
        }
    }
         public void refreshTable() {
        populateComboBox();
        DefaultTableModel model = (DefaultTableModel)jTable.getModel();
        model.setRowCount(0);
        
        for(CourseOffer co : d.getCourseSchedule(selectedSchedule).getSchedule()) {
            if(co.getFacultyProfile() ==f){
            Object row[] = new Object[3];
            row[0] = co.getCourseNumber();
            row[1] = co.getRoomNumber();
            row[2] = co.getRegisteredSeats();
            model.addRow(row);
            }
        }
        
    }
    
    private void populateComboBox(){
        semesterComboBox.removeAllItems();
        for(String semester: d.getMasterCourseCatalog().keySet()){
            semesterComboBox.addItem(semester);
        }
        semesterComboBox.setSelectedItem(selectedSchedule);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JButton manageJButton;
    private javax.swing.JComboBox<String> semesterComboBox;
    private javax.swing.JLabel semesterLabel;
    private javax.swing.JLabel viewClassJLabel;
    // End of variables declaration//GEN-END:variables


}
