/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.admin;



import java.awt.CardLayout;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.CourseSchedule.CourseOffer;
import model.CourseSchedule.CourseSchedule;
import model.Department.Department;

/**
 *
 * @author piyush
 */
public class CourseScheduleJPanel extends javax.swing.JPanel {

    JPanel workArea;
    Department d;
    String selectedSchedule = "Fall2020";
    /**
     * Creates new form ViewSupplier
     */
    public CourseScheduleJPanel(JPanel workArea,Department d ) {
        initComponents();
        this.workArea = workArea;
        this.d = d;
        
        
        
        refreshTable();
        
    }
    
    public void refreshTable() {
        populateComboBox();
        DefaultTableModel model = (DefaultTableModel)tblCourses.getModel();
        model.setRowCount(0);
        
        for(CourseOffer co : d.getCourseSchedule(selectedSchedule).getSchedule()) {
            Object row[] = new Object[5];
            row[0] = co.getSubjectCourse().getName();
            row[1] = co.getCourseNumber();
            row[2] = co.getRegisteredSeats();
            row[3] = co.getRoomNumber();
            if(co.getFacultyProfile()==null){
                row[4] = "NA";
            }
            else{
                 row[4] = co.getFacultyProfile().getPerson().getPersonId();
            }
            model.addRow(row);
        }
        
    }
    
    private void populateComboBox(){
        semesterComboBox.removeAllItems();
        for(String semester: d.getMasterCourseCatalog().keySet()){
            semesterComboBox.addItem(semester);
        }
        semesterComboBox.setSelectedItem(selectedSchedule);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdd = new javax.swing.JButton();
        lblCourse = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        tblCourses = new javax.swing.JTable();
        semesterComboBox = new javax.swing.JComboBox<>();
        semesterLabel = new javax.swing.JLabel();
        professorButton = new javax.swing.JButton();
        createSemesterButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        btnAdd.setText("Add Course Offer");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        lblCourse.setText("Course Schedule");

        jScrollPane.setBackground(new java.awt.Color(255, 255, 255));

        tblCourses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Number", "Registered Students", "Room Number", "Professor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane.setViewportView(tblCourses);

        semesterComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        semesterComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                semesterComboBoxItemStateChanged(evt);
            }
        });
        semesterComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semesterComboBoxActionPerformed(evt);
            }
        });

        semesterLabel.setText("Semester:");

        professorButton.setText("Assign Professor");
        professorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                professorButtonActionPerformed(evt);
            }
        });

        createSemesterButton.setText("Create New Semester");
        createSemesterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createSemesterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAdd)
                                .addGap(35, 35, 35)
                                .addComponent(professorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(57, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(createSemesterButton)
                        .addGap(199, 199, 199)
                        .addComponent(lblCourse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(semesterLabel)
                        .addGap(18, 18, 18)
                        .addComponent(semesterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourse)
                    .addComponent(semesterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(semesterLabel)
                    .addComponent(createSemesterButton))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(professorButton))
                .addContainerGap(302, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

        //int i=1;
        CourseOfferJPanel as = new CourseOfferJPanel(workArea,d.getCourseSchedule(selectedSchedule),d);

        workArea.add("AddCourseOffer", as);
        CardLayout layout = (CardLayout)workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnAddActionPerformed

    private void professorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_professorButtonActionPerformed
       int i = tblCourses.getSelectedRow();
       if(i<0){
           JOptionPane.showMessageDialog(this,"Please Select a Course Offer" );
           return;
       }
        AssignProfessorJPanel as = new AssignProfessorJPanel(workArea,d.getCourseSchedule(selectedSchedule).getSchedule().get(i), d.getFacultyDirectory());

        workArea.add("AssignProfessor", as);
        CardLayout layout = (CardLayout)workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_professorButtonActionPerformed

    private void createSemesterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createSemesterButtonActionPerformed
      String semesterName = JOptionPane.showInputDialog("Enter New Semester Name");
      d.newCourseSchedule(semesterName);
      //semesterComboBox.addItem(semesterName);
      //semesterComboBox.setSelectedItem(semesterName);
      selectedSchedule = semesterName;
      refreshTable();
    }//GEN-LAST:event_createSemesterButtonActionPerformed

    private void semesterComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_semesterComboBoxItemStateChanged
       
    }//GEN-LAST:event_semesterComboBoxItemStateChanged

    private void semesterComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semesterComboBoxActionPerformed
       Object o = semesterComboBox.getSelectedItem();
       if(o!=null){
        selectedSchedule = semesterComboBox.getSelectedItem().toString();
        refreshTable();
       }
    }//GEN-LAST:event_semesterComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton createSemesterButton;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel lblCourse;
    private javax.swing.JButton professorButton;
    private javax.swing.JComboBox<String> semesterComboBox;
    private javax.swing.JLabel semesterLabel;
    private javax.swing.JTable tblCourses;
    // End of variables declaration//GEN-END:variables
}
