/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.admin;

import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.CourseCatalog.Course;
import model.CourseCatalog.CourseCatalog;
import model.CourseSchedule.CourseOffer;
import model.CourseSchedule.CourseSchedule;
import model.Department.Department;
import model.Persona.Faculty.FacultyProfile;

/**
 *
 * @author Piyush
 */
public class CourseOfferJPanel extends javax.swing.JPanel {
    JPanel workArea;
    CourseSchedule currentSchedule;
    CourseCatalog courseCatalog;
    Department department;
    /**
     * Creates new form CourseOfferJPanel
     */
    public CourseOfferJPanel(JPanel w, CourseSchedule c, Department d) {
        workArea = w;
        currentSchedule = c;
        courseCatalog = d.getCourseCatalog();
        department = d;
        initComponents();
        populateComboBoxes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        facultyComboBox = new javax.swing.JComboBox<>();
        lblRoom = new javax.swing.JLabel();
        txtRoom = new javax.swing.JTextField();
        lblProfessor = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        lblCourse = new javax.swing.JLabel();
        courseComboBox = new javax.swing.JComboBox<>();
        lblTitle = new javax.swing.JLabel();

        lblRoom.setText("Room Number:");

        lblProfessor.setText("Professor ID:");

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        lblCourse.setText("Course:");

        courseComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseComboBoxActionPerformed(evt);
            }
        });

        lblTitle.setText("Course Offer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProfessor)
                            .addComponent(lblRoom)
                            .addComponent(lblCourse))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(facultyComboBox, 0, 238, Short.MAX_VALUE)
                            .addComponent(txtRoom, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                            .addComponent(courseComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(lblTitle)))
                .addContainerGap(101, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(saveButton)
                .addGap(213, 213, 213))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(courseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblProfessor)
                            .addComponent(facultyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addComponent(lblRoom))
                    .addComponent(txtRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(saveButton)
                .addContainerGap(166, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
         CourseOffer c = currentSchedule.newCourseOffer(courseComboBox.getSelectedItem().toString());
        if(!txtRoom.getText().equals("")){
            c.setRoomNumber(txtRoom.getText());
        }
        if(facultyComboBox.getSelectedIndex()!= 0){
            c.assignAsTeacher(department.getFacultyDirectory().findTeachingFaculty(facultyComboBox.getSelectedItem().toString()));
        }
      
        JOptionPane.showMessageDialog(this, "Course offer successfully added");
        backAction();
        
    }//GEN-LAST:event_saveButtonActionPerformed

    private void courseComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseComboBoxActionPerformed
       
    }//GEN-LAST:event_courseComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> courseComboBox;
    private javax.swing.JComboBox<String> facultyComboBox;
    private javax.swing.JLabel lblCourse;
    private javax.swing.JLabel lblProfessor;
    private javax.swing.JLabel lblRoom;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField txtRoom;
    // End of variables declaration//GEN-END:variables

    private void populateComboBoxes() {
       for(Course c : courseCatalog.getCourseList()){
           courseComboBox.addItem(c.getNumber());
       }
       facultyComboBox.addItem("No Teacher Assigned");
       for(FacultyProfile f : department.getFacultyDirectory().getTeacherlist()){
           facultyComboBox.addItem(f.getPerson().getPersonId());
       }
    }
    
    private void backAction() {
        workArea.remove(this);
        Component[] componentArray = workArea.getComponents();
        Component component = componentArray[componentArray.length - 1];
        //workArea.remove(this);
        CourseScheduleJPanel cs = (CourseScheduleJPanel) component;
        cs.refreshTable();
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.previous(workArea);
    }
    
}
