/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.student;

import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.CourseCatalog.Course;
import model.CourseCatalog.CourseCatalog;
import model.CourseSchedule.CourseOffer;
import model.CourseSchedule.CourseSchedule;
import model.CourseSchedule.SeatAssignment;
import model.Persona.StudentProfile;

/**
 *
 * @author piyush
 */
public class RegisterClassesJPanel extends javax.swing.JPanel {
JPanel workArea;
StudentProfile s;
HashMap<String,CourseSchedule> mastercoursecatalog;
String selectedSemester;
    /**
     * Creates new form RegisterClassesJPanel
     */
    public RegisterClassesJPanel(JPanel workArea , StudentProfile s,HashMap<String,CourseSchedule> mastercoursecatalog) {
        this.workArea = workArea;
        this.s = s;
        this.mastercoursecatalog = mastercoursecatalog;
        initComponents();
        populateComboBox();
        refreshTable();
        
    }
    
    
    
    private void populateComboBox(){
        semesterComboBox.removeAllItems();
        for(String semester: mastercoursecatalog.keySet()){
            semesterComboBox.addItem(semester);
        }
        semesterComboBox.setSelectedItem(selectedSemester);
    }
        public void refreshTable() {
        
        DefaultTableModel model = (DefaultTableModel)tblCourses.getModel();
        model.setRowCount(0);
        
        for(CourseOffer co : mastercoursecatalog.get(selectedSemester).getSchedule()) {
            Object row[] = new Object[4];
            row[0] = co.getSubjectCourse().getName();
            row[1] = co.getCourseNumber();
           
            row[3] = co.getRoomNumber();
            if(co.getFacultyProfile()==null){
                row[2] = "NA";
            }
            else{
                 row[2] = co.getFacultyProfile().getPerson().getPersonId();
            }
            model.addRow(row);
        }
        model = (DefaultTableModel) tblMyClasses.getModel();
        model.setRowCount(0);
        if(s.getTranscript().getCourseLoadBySemester(selectedSemester)==null){
            s.getTranscript().newCourseLoad(selectedSemester);
        }
        for(SeatAssignment sa : s.getTranscript().getCourseLoadBySemester(selectedSemester).getSeatAssignments()) {
            Object row[] = new Object[3];
            CourseOffer co = sa.getCourseOffer();
            
             row[0] = co.getSubjectCourse().getName();
            
           
            row[2] = co.getRoomNumber();
            if(co.getFacultyProfile()==null){
                row[1] = "NA";
            }
            else{
                 row[1] = co.getFacultyProfile().getPerson().getPersonId();
            }
            
            model.addRow(row);
            
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourses = new javax.swing.JTable();
        semesterJLabel = new javax.swing.JLabel();
        registerJLabel = new javax.swing.JLabel();
        semesterComboBox = new javax.swing.JComboBox<>();
        addClassJButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMyClasses = new javax.swing.JTable();
        myClassesJLabel = new javax.swing.JLabel();

        tblCourses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Class Name", "CRN Number", "Professor", "Room Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCourses);

        semesterJLabel.setText("Semester");

        registerJLabel.setText("Register For Classes");

        semesterComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semesterComboBoxActionPerformed(evt);
            }
        });

        addClassJButton.setText("Add Class");
        addClassJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClassJButtonActionPerformed(evt);
            }
        });

        tblMyClasses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Class Name", "Professor", "Room Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblMyClasses);

        myClassesJLabel.setText("My Classes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(addClassJButton)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(224, 224, 224)
                            .addComponent(myClassesJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(registerJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(semesterJLabel)
                        .addGap(18, 18, 18)
                        .addComponent(semesterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerJLabel)
                    .addComponent(semesterJLabel)
                    .addComponent(semesterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addClassJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(myClassesJLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void semesterComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semesterComboBoxActionPerformed
        Object o = semesterComboBox.getSelectedItem();
       if(o!=null){
        selectedSemester = semesterComboBox.getSelectedItem().toString();
        refreshTable();
       }
    }//GEN-LAST:event_semesterComboBoxActionPerformed

    private void addClassJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addClassJButtonActionPerformed
           int i = tblCourses.getSelectedRow();
           if(i<0){
               JOptionPane.showMessageDialog(this,"Please Select Class");
           return;
           }
           SeatAssignment sa = s.getTranscript().getCourseLoadBySemester(selectedSemester).newSeatAssignment(mastercoursecatalog.get(selectedSemester).getSchedule().get(i));
           refreshTable();
           if(sa==null){
           JOptionPane.showMessageDialog(this,"Class Full");
               return;
           }
           JOptionPane.showMessageDialog(this,"Class Added");
    }//GEN-LAST:event_addClassJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addClassJButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel myClassesJLabel;
    private javax.swing.JLabel registerJLabel;
    private javax.swing.JComboBox<String> semesterComboBox;
    private javax.swing.JLabel semesterJLabel;
    private javax.swing.JTable tblCourses;
    private javax.swing.JTable tblMyClasses;
    // End of variables declaration//GEN-END:variables
}
